[project]
name = "env"
version = "0.1.0"
description = ""
authors = [
    {name = "Andrii-Bezkrovnyi",email = "andrii@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Django==3.1",
    "beautifulsoup4",
    "Pillow==2.7.0"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
